name: TypeScript Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repo Directory
        uses: actions/checkout@v2
      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v2
        with:
          node-version: "18.16.0"
      - name: Pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
            version: 8
            run_install: true
            auto-install-peers: false
  unittest:
    name: Run UnitTest
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repo Directory
        uses: actions/checkout@v2
      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v2
        with:
          node-version: "18.16.0"
      - name: Pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
            version: 8
            run_install: true
            auto-install-peers: false
      - name: run unit test
        run: pnpm run test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ${{ github.workspace }}/coverage
